---
- name: variables processing
  set_fact:
    ovf_file: "{{ovf_file | default('files/Nested_ESXi7.0_Appliance_Template_v1.ova')}}"
    ovf_url: "{{ovf_url | default('https://download3.vmware.com/software/vmw-tools/nested-esxi/Nested_ESXi7.0_Appliance_Template_v1.ova')}}"
    vm_name: "{{vm_name | default('esxvm') }}"
    vm_network: "{{vm_network | default('VM Network') }}"
    vm_num_cpus: "{{vm_num_cpus | default(2) }}"
    ovf_ssh: "{{ovf_ssh | default('true') }}"
    ovf_createvmfs: "{{ovf_createvmfs |default('false') }}"

- vmware_deploy_ovf:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    cluster: '{{ vcenter_cluster }}'
    datastore: '{{ vm_datastore }}'
    name: '{{ vm_name }}'
    ovf: '{{ ovf_file }}'
    disk_provisioning: thin
    power_on: no
    wait_for_ip_address: false
    networks: "{u'VM Network':u'{{ vm_network }}'}"
    inject_ovf_env: true
    properties:
      guestinfo.hostname: "{{ovf_hostname|default('')}}"
      guestinfo.ipaddress: "{{ovf_address|default('')}}"
      guestinfo.netmask: "{{ovf_netmask|default('')}}"
      guestinfo.gateway: "{{ovf_gateway|default('')}}"
      guestinfo.vlan: "{{ovf_vlan|default('')}}"
      guestinfo.dns: "{{ovf_dns|default('')}}"
      guestinfo.domain: "{{ovf_domain|default('')}}"
      guestinfo.ntp: "{{ovf_ntp|default('pool.ntp.org')}}"
      guestinfo.syslog: "{{ovf_syslog|default('')}}"
      guestinfo.password: "{{ovf_password|default('VMware1!')}}"
      guestinfo.ssh: '{{ovf_ssh|string}}'
      guestinfo.createvmfs: '{{ovf_createvmfs|string}}'
  delegate_to: localhost
  retries: 10
  delay: 60
  register: result
  until: result is succeeded
  when: vcenter_address != esxi_address

- name: Adjust VM Sizing - cpu and mem
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    name: '{{ vm_name }}'
    state: present
    hardware:
      memory_mb: '{{ vm_memory_mb|int }}'
      num_cpus: '{{ vm_num_cpus|int }}'
  delegate_to: localhost
  when: 
    - vcenter_address != esxi_address

- name: Adjust VM Sizing - disk1
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    name: '{{ vm_name }}'
    state: present
    disk:
    - size_gb: "{{ vm_disk1_size_gb|int }}"
      controller_type: paravirtual
      controller_number: 0
      unit_number: 1
      datastore: '{{ vm_datastore }}'
      type: thin
    hardware:
      memory_mb: '{{ vm_memory_mb|int }}'
      num_cpus: '{{ vm_num_cpus|int }}'
  delegate_to: localhost
  when: 
    - vcenter_address != esxi_address
    - vm_disk1_size_gb is defined
    - vm_disk1_size_gb|int > 0

- name: Adjust VM Sizing - disk2
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    name: '{{ vm_name }}'
    state: present
    disk:
    - size_gb: "{{ vm_disk2_size_gb|int }}"
      controller_type: paravirtual
      controller_number: 0
      unit_number: 2
      datastore: '{{vm_datastore}}'
      type: thin
    hardware:
      memory_mb: '{{ vm_memory_mb|int }}'
      num_cpus: '{{ vm_num_cpus|int }}'
  delegate_to: localhost
  when: 
    - vcenter_address != esxi_address
    - vm_disk2_size_gb is defined
    - vm_disk2_size_gb|int > 0

- name: Create Network Adapters
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_address }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    cluster: '{{ vcenter_cluster }}'
    name: '{{ vm_name }}'
    state: present
    networks: '{{network_adapters}}'
  delegate_to: localhost
  register: create_network_adapters
  when:
    - network_adapters is defined
    - network_adapters is not false

- name: Power-On the virtual machine
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    name: '{{ vm_name }}'
    state: poweredon
  delegate_to: localhost
  register: powerstate
  when: vcenter_address != esxi_address

# When deploying to a standalone host custom sizing/disks are not possible
# but we can still deploy it with default sizings
- vmware_deploy_ovf:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    cluster: '{{ vcenter_cluster }}'
    datastore: '{{ vm_datastore }}'
    name: '{{ vm_name }}'
    ovf: '{{ ovf_file }}'
    disk_provisioning: thin
    power_on: yes
    wait_for_ip_address: false
    networks: "{u'VM Network':u'{{ vm_network }}'}"
    inject_ovf_env: true
    properties:
      guestinfo.hostname: "{{ovf_hostname|default('')}}"
      guestinfo.ipaddress: "{{ovf_address|default('')}}"
      guestinfo.netmask: "{{ovf_netmask|default('')}}"
      guestinfo.gateway: "{{ovf_gateway|default('')}}"
      guestinfo.vlan: "{{ovf_vlan|default('')}}"
      guestinfo.dns: "{{ovf_dns|default('')}}"
      guestinfo.domain: "{{ovf_domain|default('')}}"
      guestinfo.ntp: "{{ovf_ntp|default('pool.ntp.org')}}"
      guestinfo.syslog: "{{ovf_syslog|default('')}}"
      guestinfo.password: "{{ovf_password|default('VMware1!')}}"
      guestinfo.ssh: '{{ovf_ssh|string}}'
      guestinfo.createvmfs: '{{ovf_createvmfs|string}}'
  delegate_to: localhost
  retries: 10
  delay: 60
  register: result
  until: result is succeeded
  when: vcenter_address == esxi_address