- name: Get VMID by Name
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    validate_certs: false
    node: "{{ pve_node }}"
    name: '{{ vm_name|replace("_", "-") }}'
    state: current
  register: create_vm
  delegate_to: localhost

- name: Reboot Guest
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    validate_certs: false
    state: restarted
    name: '{{ vm_name|replace("_", "-") }}'
  delegate_to: localhost
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  ignore_errors: true

- name: Wait for 60 seconds
  wait_for: timeout=60
  delegate_to: localhost

- name: Wait until QEMU agent reports a valid IPv4 address
  ansible.builtin.command: "qm guest cmd {{ create_vm.vmid }} network-get-interfaces"
  delegate_to: temp_host
  register: qm_output
  changed_when: false
  # Retry logic
  until: >
    qm_output.rc == 0 and 
    (qm_output.stdout | from_json) 
    | rejectattr('name', 'equalto', 'lo') 
    | map(attribute='ip-addresses') 
    | flatten 
    | selectattr('ip-address-type', 'equalto', 'ipv4') 
    | list 
    | length > 0
  retries: 60                    # Total number of attempts
  delay: 60  

