- name: Get VMID by Name
  community.general.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    node: "{{ pve_node }}"
    name: '{{ vm_name|replace("_", "-") }}'
    state: current
  register: create_vm
  delegate_to: localhost

- name: run extra commands
  command:
    cmd: 'qm guest exec {{ create_vm.vmid }} --timeout 3600 -- powershell.exe -command "({{item}})" |grep exitcode|grep 0'
  delegate_to: temp_host
  ignore_errors: true
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  loop_control:
    pause: 10
  loop: "{{extra_commands}}"
  when: extra_commands is defined