---
- name: "Install Requirements"
  hosts: localhost
  gather_facts: false
  tasks:

  - name: install python modules
    ansible.builtin.pip:
      name: "{{item}}"
    with_items:
      - pycdlib
      - pywinrm
      - pyvmomi
      - netapp-lib
      - jmespath
      - proxmoxer
      - passlib

  - name: install community.general
    ansible.builtin.command: ansible-galaxy collection install community.general

  - name: install remaining collections
    community.general.ansible_galaxy_install:
      type: both
      requirements_file: requirements.yml

  - name: Install mtools
    ansible.builtin.package:
      name: mtools
      state: present
    become: True
    become_user: root
    ignore_errors: True




