---
- name: Create new Active-Directory Domain & Forest using vmshell
  hosts: localhost
  gather_facts: no  
  vars_files:
   - vars/main.yml
  tasks:
    - include_tasks: tasks/Create_New_Active_Directory_using_vm_shell.yml
      vars:
        vm_name: lab_ansible_v2_dc01
        vm_network: "lab_ansible_v2_1"
        vm_password: P@ssw0rd
        vm_dns_server: 192.168.0.1
        vm_domain: lab.local
