- name: Get VMID 
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: current
    name: '{{ vm_name|replace("_", "-") }}'
    node: "{{ pve_node }}"
  delegate_to: localhost
  register: create_vm

# On proxmox you canhave up to 31 virtio disks
# They can all be declared on shelf 0 or can span over to shelf1
- name: Build Disk Shelf 0 
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi{{item-1}} {{pve_datastore}}:{{shelf0_disk_size / 1024}}"
  delegate_to: temp_host
  when:
    - shelf0_disk_size|default("") != ""
    - item <= shelf0_disk_count|default(shelf0_qty)|int
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  ignore_errors: true

# on Proxmox all of these lab on the 0b adapter anyway
# but the shelf construct is maintained for consistency with the
# VMware based version's 4 controllers / 15 drives each topology
- name: Build Disk Shelf 1
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi{{ item - 1 + shelf0_disk_count }} {{pve_datastore}}:{{shelf1_disk_size / 1024}}"
  delegate_to: temp_host
  when:
    - shelf1_disk_size|default("") != ""
    - item <= shelf1_disk_count|default(shelf1_qty)|int
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  ignore_errors: true

# Spanning the disks accross shelf definitions allows for different disk sizes
- name: Build Disk Shelf 2
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi{{ item - 1 + shelf0_disk_count + shelf1_disk_count }} {{pve_datastore}}:{{shelf2_disk_size / 1024}}"
  delegate_to: temp_host
  when:
    - shelf2_disk_size|default("") != ""
    - item <= shelf2_disk_count|default(shelf2_qty)|int
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  ignore_errors: true

# Spanning the disks accross shelf definitions allows for different disk sizes
- name: Build Disk Shelf 3
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi{{ item - 1 + shelf0_disk_count + shelf1_disk_count + shelf2_disk_count }} {{pve_datastore}}:{{shelf3_disk_size / 1024}}"
  delegate_to: temp_host
  when:
    - shelf3_disk_size|default("") != ""
    - item <= shelf3_disk_count|default(shelf3_qty)|int
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  ignore_errors: true

  