- name: Create new VM 
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: present
    name: '{{ vm_name|replace("_", "-") }}'
    node: "{{ pve_node }}"
    net: '{{ networks }}'
    serial:
      serial0: 'socket'
      serial1: 'socket'
    vga: serial0
    cpu: host
    sockets: '{{ vm_num_cpus|int }}'
    vcpus: '{{ vm_num_cpus|int }}'
    memory: '{{ vm_memory_mb |int}}'
    agent: true
    scsihw: virtio-scsi-pci
  delegate_to: localhost
  register: create_vm
  retries: 3
  delay: 10
  until: create_vm is succeeded

- debug: 
    msg: "{{ create_vm.vmid }}"

- name: Create partner VM 
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: present
    name: '{{ partner_name|replace("_", "-") }}'
    node: "{{ pve_node }}"
    net: '{{ networks }}'
      # net0: 'e1000,bridge={{ pve_cluster_network }}'
      # net1: 'e1000,bridge={{ pve_cluster_network }}'
      # net2: 'e1000,bridge={{ pve_data_network }}'
      # net3: 'e1000,bridge={{ pve_data_network }}'
    serial:
      serial0: 'socket'
      serial1: 'socket'
    vga: serial0
    cpu: host
    sockets: '{{ vm_num_cpus|int }}'
    vcpus: '{{ vm_num_cpus|int }}'
    memory: '{{ vm_memory_mb |int}}'
    agent: true
    scsihw: virtio-scsi-pci
  delegate_to: localhost
  register: create_partner_vm
  retries: 3
  delay: 10
  until: create_partner_vm is succeeded

- debug: 
    msg: "{{ create_partner_vm.vmid }}"

- name: Copy disks to temporary storage
  copy:
    src: "{{ playbook_dir }}/files/{{vm_name}}/vsim-NetAppDOT-simulate-{{item}}.vmdk"
    dest: "{{ iso_path }}/{{ vm_name }}-{{item}}.vmdk"
  delegate_to: temp_host
  loop:
    - disk1
    - disk2
    - disk3

- name: Copy partner disks to temporary storage
  copy:
    src: "{{ playbook_dir }}/files/{{partner_name}}/vsim-NetAppDOT-simulate-{{item}}.vmdk"
    dest: "{{ iso_path }}/{{ partner_name }}-{{item}}.vmdk"
  delegate_to: temp_host
  loop:
    - disk1
    - disk2
    - disk3

- name: import disks
  shell:  
    cmd: "qm disk import {{ create_vm.vmid }} {{ iso_path }}/{{ vm_name }}-{{item}}.vmdk {{pve_datastore}} --format raw"
  delegate_to: temp_host
  loop:
    - disk1
    - disk2
    - disk3

- name: import partner disks
  shell:  
    cmd: "qm disk import {{ create_partner_vm.vmid }} {{ iso_path }}/{{ partner_name }}-{{item}}.vmdk {{pve_datastore}} --format raw"
  delegate_to: temp_host
  loop:
    - disk1
    - disk2
    - disk3

- name: Attach disks
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --ide{{item}} file={{pve_datastore}}:vm-{{create_vm.vmid}}-disk-{{item}}"
  delegate_to: temp_host
  loop:
   - 0
   - 1
   - 2

- name: Attach partner disks
  shell:  
    cmd: "qm set {{ create_partner_vm.vmid }} --ide{{item}} file={{pve_datastore}}:vm-{{create_partner_vm.vmid}}-disk-{{item}}"
  delegate_to: temp_host
  loop:
   - 0
   - 1
   - 2

- name: Remove disks from temporary storage
  ansible.builtin.file:
    path: "{{ iso_path }}/{{ vm_name }}-{{item}}.vmdk"
    state: absent
  delegate_to: temp_host
  loop:
    - disk1
    - disk2
    - disk3

- name: Remove partner disks from temporary storage
  ansible.builtin.file:
    path: "{{ iso_path }}/{{ partner_name }}-{{item}}.vmdk"
    state: absent
  delegate_to: temp_host
  loop:
    - disk1
    - disk2
    - disk3

- name: Set boot order
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --bootdisk ide0 --boot order=ide0"
  delegate_to: temp_host

# On proxmox you canhave up to 31 virtio disks
# They can all be declared on shelf 0 or can span over to shelf1
- name: Build Disk Shelf 0 
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi{{item-1}} {{pve_datastore}}:{{shelf0_disk_size / 1024}}"
  delegate_to: temp_host
  when:
    - shelf0_disk_size|default("") != ""
    - item <= shelf0_disk_count|default(shelf0_qty)|int
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  ignore_errors: true

# on Proxmox all of these lab on the 0b adapter anyway
# but the shelf construct is maintained for consistency with the
# VMware based version's 4 controllers / 15 drives each topology
- name: Build Disk Shelf 1
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi{{ item - 1 + shelf0_disk_count }} {{pve_datastore}}:{{shelf1_disk_size / 1024}}"
  delegate_to: temp_host
  when:
    - shelf1_disk_size|default("") != ""
    - item <= shelf1_disk_count|default(shelf1_qty)|int
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  ignore_errors: true

# Spanning the disks accross shelf definitions allows for different disk sizes
- name: Build Disk Shelf 2
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi{{ item - 1 + shelf0_disk_count + shelf1_disk_count }} {{pve_datastore}}:{{shelf2_disk_size / 1024}}"
  delegate_to: temp_host
  when:
    - shelf2_disk_size|default("") != ""
    - item <= shelf2_disk_count|default(shelf2_qty)|int
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  ignore_errors: true

# Spanning the disks accross shelf definitions allows for different disk sizes
- name: Build Disk Shelf 3
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi{{ item - 1 + shelf0_disk_count + shelf1_disk_count + shelf2_disk_count }} {{pve_datastore}}:{{shelf3_disk_size / 1024}}"
  delegate_to: temp_host
  when:
    - shelf3_disk_size|default("") != ""
    - item <= shelf3_disk_count|default(shelf3_qty)|int
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  ignore_errors: true

- name: Start VM
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: started
    name: '{{ vm_name|replace("_", "-") }}'
  delegate_to: localhost
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  ignore_errors: true
  