---
- name: Remove VMs if state is absent or forced
  include_tasks: absent.yml
  when: state == "absent" or state == "force"

- name: build vm on VMware
  include_tasks: vmw_main.yml
  when: 
    - state != "absent"
    - vcenter_address ~ esxi_address != ''
    - pve_address == ''

- name: build vm on PVE
  include_tasks: pve_main.yml
  when:
    - state != "absent"
    - pve_address != ''
