- name: map login variables
  set_fact:
    vcenter_address: "{{ esxi_address }}"
    vcenter_username: "{{ esxi_username }}"
    vcenter_password: "{{ esxi_password }}"
    vcenter_datacenter: "ha-datacenter"
  delegate_to: localhost
  when: vcenter_address == ''

- name: upload install iso
  include_tasks: vmw_upload_install_iso.yml

- name: Build VM
  include_tasks: vmw_build_vm.yml