- name: Join Domain
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}' 
    validate_certs: false
    vm_username: "{{ vm_username }}"
    vm_password: '{{ vm_password_new }}'
    vm_id:       '{{ vm_name }}'
    vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
    vm_shell_args: " -command \"({{item}})\""
    wait_for_process: true
  delegate_to: localhost
  loop:
    - "Add-Computer -DomainName {{domain}} -credential (New-Object System.Management.Automation.PSCredential 'administrator@{{domain}}', (convertto-securestring {{ vm_password_new }} -AsPlainText -Force))"
  retries: 3
  delay: 30
  register: result           
  until: result is succeeded    
  ignore_errors: true
  when: join_domain|default(false)|string|lower != "false"

# - name: reboot guest
#   include_tasks: reboot_guest.yml
#   when: join_domain|default(false)|string|lower != "false"