
- name: Get VMID 
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: current
    name: '{{ vm_name|replace("_", "-") }}'
    node: "{{ pve_node }}"
  delegate_to: localhost
  register: create_vm

- name: CentOS 7 defibrilator
  shell:
    cmd: "qm guest exec {{ create_vm.vmid }} --timeout 600 -- /bin/bash -c \"{{item}}\" |grep exitcode|grep 0"
  delegate_to: temp_host
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  ignore_errors: true
  loop_control:
    pause: 5
  loop: 
    - "sed -i -e 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*"
    - "sed -i -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
    - "yum-config-manager --enable extras"
    - "yum install -y dnf"
  when:
    - distro|lower == "centos"
    - version|float >= 7
    - version|float < 8
  
- name: CentOS 8 defibrilator
  shell:
    cmd: "qm guest exec {{ create_vm.vmid }} --timeout 600 -- /bin/bash -c \"{{item}}\" |grep exitcode|grep 0"
  delegate_to: temp_host
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  ignore_errors: true
  loop_control:
    pause: 5
  loop: 
    - "sed -i -e 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*"
    - "sed -i -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
  when:
    - distro|lower == "centos"
    - version|float >= 8

- name: scale the paywall
  shell:
    cmd: "qm guest exec {{ create_vm.vmid }} --timeout 600 -- /bin/bash -c \"{{item}}\" |grep exitcode|grep 0"
  delegate_to: temp_host
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  ignore_errors: true
  loop_control:
    pause: 5
  loop:
    - "subscription-manager register --org {{ rhsm_orgid }} --activationkey {{ rhsm_activationkey }}"
    - "subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms"
    - "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
  when: distro|lower == "rhel"

- name: Install xRDP
  shell:
    cmd: "qm guest exec {{ create_vm.vmid }} --timeout 600 -- /bin/bash -c \"{{item}}\" |grep exitcode|grep 0"
  delegate_to: temp_host
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  ignore_errors: true
  loop_control:
    pause: 5
  loop:
    - "dnf install -y epel-release"
    - "dnf install -y xrdp"
    - "xrdp-keygen xrdp auto"
    - "systemctl enable xrdp --now"
    - "firewall-cmd --permanent --add-port=3389/tcp"
    - "firewall-cmd --reload"
  when: install_xrdp|default(false)

- name: Install Ansible and related components
  shell:
    cmd: "qm guest exec {{ create_vm.vmid }} --timeout 600 -- /bin/bash -c \"{{item}}\" |grep exitcode|grep 0"
  delegate_to: temp_host
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  ignore_errors: true
  loop_control:
    pause: 5
  loop:
    - "dnf install -y epel-release"
    - "dnf install -y ansible"
    - "dnf install -y python3-pip"
    - "pip3 install --upgrade pip"
    # - "pip3 install ansible"
    - "pip3 install netapp-lib"
    - "pip3 install pyvmomi"
    - "pip3 install pywinrm"
    - "pip3 install pycdlib"
  when: install_ansible|default(false)

- name: Run extra shell command via vm_shell
  shell:
    cmd: "qm guest exec {{ create_vm.vmid }} --timeout 3600 -- /bin/bash -c \"{{item}}\" |grep exitcode|grep 0"
  delegate_to: temp_host
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  ignore_errors: true
  loop_control:
    pause: 5
  loop: "{{ extra_commands }}"
  when:
    - extra_commands is defined
