---


## Install ISO handler
- name: Check if install ISO exists
  community.vmware.vsphere_file:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter: "{{vcenter_datacenter}}"
    datastore: "{{ iso_datastore }}"
    path: "{{ install_iso }}"
    state: file
  register: install_iso_exists
  delegate_to: localhost
  ignore_errors: true

# upload install iso
- name: upload install iso
  include_tasks: upload_install_iso.yml
  when: install_iso_exists.failed

# check again
- name: Check if install ISO exists
  community.vmware.vsphere_file:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter: "{{vcenter_datacenter}}"
    datastore: "{{ iso_datastore }}"
    path: "{{ install_iso }}"
    state: file
  register: install_iso_exists2
  delegate_to: localhost
  ignore_errors: true

# last resort, have esx download it
- name: download via esx
  include_tasks: download_via_esx.yml
  when: install_iso_exists2.failed

- name: Create VM
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}' 
    validate_certs: no 
    datacenter: "{{vcenter_datacenter}}"
    cluster: '{{vcenter_cluster}}'    
    folder: /
    name: '{{ vm_name }}'
    state: present
    guest_id: ubuntu64Guest
    cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '[{{ iso_datastore }}] {{ install_iso }}'
    disk:
    - size_gb: '{{ vm_disk_gb | default(40) }}'
      type: thin
      datastore: '{{ vm_datastore }}'
    hardware:
      memory_mb: '{{ vm_memory_mb | default(2048) }}'
      num_cpus: '{{ vm_num_cpus | default(2) }}'
      nested_virt: '{{ nested_virtualization|default(true) }}'
      scsi: lsilogicsas
    networks:
    - name: "{{ vm_network | default('VM Network') }}"
      device_type: e1000
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy_vm

- name: Set boot order
  community.vmware.vmware_guest_boot_manager:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no  
    name: '{{ vm_name }}'
    boot_delay: 1000
    enter_bios_setup: False
    boot_retry_enabled: True
    boot_retry_delay: 20000
    boot_firmware: bios
    secure_boot_enabled: False
    boot_order:
      - disk
      - cdrom
      - ethernet
      - floppy
  delegate_to: localhost
  register: vm_boot_order

- name: Power-On the virtual machine
  community.vmware.vmware_guest_powerstate:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'    
    validate_certs: no 
    name: '{{ vm_name }}'
    state: powered-on
  delegate_to: localhost
  register: powerstate

- name: Wait for 60 seconds for boot
  wait_for: timeout=60
  delegate_to: localhost

- name: Select Keymap
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds 
  wait_for: timeout=5
  delegate_to: localhost

- name: Welcome To Setup
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds 
  wait_for: timeout=5
  delegate_to: localhost

- name: Accept EULA
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - LEFTARROW
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds 
  wait_for: timeout=5
  delegate_to: localhost

- name: Disk Storage Configuration
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - TAB
     - TAB
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds 
  wait_for: timeout=5
  delegate_to: localhost

- name: media source 
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - TAB
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds 
  wait_for: timeout=5
  delegate_to: localhost

- name: media verification
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - UPARROW
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds 
  wait_for: timeout=10
  delegate_to: localhost

- name: set password
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    string_send: "{{ vm_password }}"
  delegate_to: localhost

- name: confirm password
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: DOWNARROW
    string_send: "{{ vm_password }}"
  delegate_to: localhost

- name: OK
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - ENTER
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds
  wait_for: timeout=5
  delegate_to: localhost

- name: set static IP
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - SPACE
     - DOWNARROW
    string_send: "{{vm_address}}"
  delegate_to: localhost

- name: set netmask
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
    string_send: "{{vm_netmask}}"
  delegate_to: localhost

- name: set gateway
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
    string_send: "{{vm_gateway}}"
  delegate_to: localhost

- name: OK
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - DOWNARROW
     - ENTER
    string_send: "{{vm_gateway}}"
  delegate_to: localhost

- name: Wait for 5 seconds
  wait_for: timeout=5
  delegate_to: localhost

- name: set hostname
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
    string_send: "{{vm_hostname}}.{{vm_domain}}"
  delegate_to: localhost

- name: set dns
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - TAB
    string_send: "{{vm_dns_server}}"
  delegate_to: localhost

- name: skip dns2
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - TAB
  delegate_to: localhost

- name: skip dns3
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - TAB
  delegate_to: localhost

- name: OK
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - TAB
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds
  wait_for: timeout=5
  delegate_to: localhost

- name: Select GEO
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - TAB
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds
  wait_for: timeout=5
  delegate_to: localhost

- name: Select City - Los Angeles
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    string_send: "lll"
  delegate_to: localhost

- name: OK
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - TAB
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds
  wait_for: timeout=5
  delegate_to: localhost

- name: NTP Server
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send:
     - ENTER
    string_send: "pool.ntp.org"
  delegate_to: localhost

- name: OK
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - TAB
     - TAB
     - TAB
     - ENTER
  delegate_to: localhost

- name: Wait for 5 seconds
  wait_for: timeout=5
  delegate_to: localhost

- name: finally proceed with install
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - LEFTARROW
     - ENTER
  delegate_to: localhost

- name: Wait for 5 minutes
  wait_for: timeout=300
  delegate_to: localhost

- name: answer one more question because why not at this point
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - ENTER
  delegate_to: localhost

- name: Wait for 8 minutes
  wait_for: timeout=480
  delegate_to: localhost

- name: and now wait for an interactive OK before rebooting
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - ENTER
  delegate_to: localhost
