- name: set version defaults 
  set_fact:
    install_iso: '{{ versions[version].install_iso }}'
    image_name:  '{{ versions[version].image_name }}'
    install_iso_url: '{{ versions[version].install_iso_url }}'
    virtio_win_gt_x64_url: '{{ versions[version].virtio_win_gt_x64_url }}'
    virtio_win_guest_tools_url: '{{ versions[version].virtio_win_guest_tools_url }}'
    vmware_tools_url: '{{ versions[version].vmware_tools_url }}'

- name: set vmw vars
  set_fact:
    host_type: "vmw"
    first_logon_commands:
      - powershell -ExecutionPolicy ByPass -File E:\ConfigureRemotingForAnsible.ps1
      - E:\files\VMware_tools.exe /S /v"/qn REBOOT=R"
      - powershell -command "new-netipaddress -InterfaceAlias Ethernet0 -IPAddress {{ vm_address }} -prefixlength {{vm_netmask_cidr}} -defaultgateway {{ vm_gateway }}"
      - powershell -command "Set-DnsClientServerAddress -InterfaceAlias Ethernet0 -ServerAddresses {{ vm_dns_server }}"
    when:
    - vcenter_address ~ esxi_address != ''

- name: set pve vars
  set_fact:
    host_type: "pve"
    include_files:
      - '{{ role_path }}/files/redhat-cert-old.cer'
      - '{{ role_path }}/files/redhat-cert.cer'
    first_logon_commands:
      - certutil -addstore -f "TrustedPublisher" E:\files\redhat-cert-old.cer
      - certutil -addstore -f "TrustedPublisher" E:\files\redhat-cert.cer
      - powershell -ExecutionPolicy ByPass -File E:\ConfigureRemotingForAnsible.ps1
      - msiexec /I E:\files\virtio-win-gt-x64.msi /qn /passive /log ".." ADDLOCAL=ALL
      - E:\files\virtio_win_guest_tools.exe /S
      - powershell -command "new-netipaddress -InterfaceAlias Ethernet -IPAddress {{ vm_address }} -prefixlength {{vm_netmask_cidr}} -defaultgateway {{ vm_gateway }}"
      - powershell -command "Set-DnsClientServerAddress -InterfaceAlias Ethernet -ServerAddresses {{ vm_dns_server }}"
    pve_vm_datastore: "{{ datastore_substitutions[vm_datastore]|default(vm_datastore) }}"
    pve_vm_network: "{{ network_substitutions[vm_network]|default(vm_network) }}"
  when:
    - pve_address != ''   

- name: Map ESXi login variables
  set_fact:
    vcenter_address: "{{ esxi_address }}"
    vcenter_username: "{{ esxi_username }}"
    vcenter_password: "{{ esxi_password }}"
    vcenter_datacenter: "ha-datacenter"
  delegate_to: localhost
  when: 
    - host_type == "vmw"
    - vcenter_address|default('') == '' 

- name: Add PVE Host to Dynamic Inventory
  add_host:
    hostname: temp_host
    group: "temp_hosts"
    ansible_host: '{{ pve_address }}'
    ansible_user: '{{ pve_username }}'
    ansible_password: '{{ pve_password }}'
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  when: 
    - host_type == 'pve'

# Domain Join Vars
- name: select vm_domain
  set_fact:
    domain: "{{vm_domain}}"
  when: join_domain|default(false)|string|lower == "true"

- name: select join_domain 
  set_fact:
    domain: "{{join_domain}}"
  when: join_domain|default(false)|string|lower != "true"

- name: map vm_password 
  set_fact:
    vm_password: "{{ vm_password | default(vm_password_new| default('') ) }}"
