state: "present"
# Path to the default ONTAP Select Standalone Evaluation OVA
ontap_version: "9.16.1"
ovf_file:    "{{role_path}}/files/{{ontap_version}}_DataONTAPv-esx-standalone-eval-nodar.ova"

disk_name: "DataONTAPv"

enable_sidl: true
node_serial_number: 99887766554433221177
# The ovf deployment option changed at 9.6
# <=9.5 use 'ONTAPSelectEVAL', 
# 9.6+ use 'ONTAPSelectEVALSmall'
# ontap_deployment_option: 'ONTAPSelectEVALSmall' 

# Default VM Name
# vm_name: ONTAPSelectEval

# Standard VM sizing for a small node
# vm_num_cpus: 4
# vm_memory_mb: 16384

# # Memory reservation should default to 100%
# # but would vary from host to host
# # This is just enough to prevent a panic
# vm_cpu_reservation_mhz: 1000        
 
# This is the disk size of the data aggregate
# The minimum supported size is 1tb
# But smaller sizes can be used for evaluation nodes   
# vm_data_disk_gb: "500"

# A production VM would be thick provisioned
# A lab eval node can be thin
# vm_disk_rovisioning: thin 

# This is all required for the cluster to instantiate itself
ontap_cluster_name: "ONTAP"
ontap_cluster_mgmt_ip: ""    
ontap_node_mgmt_ip: ""
ontap_netmask: ""
ontap_gateway: "" 
ontap_password: "Changeme!"
# ontap_dns_domain: "lab.local"
# ontap_dns_server: ""

# Some additional defaults
vm_name: "ONTAPSelect"
vm_num_cpus: "4"
vm_memory_mb: "16384"
vm_cpu_reservation_mhz: "2000"
ontap_deployment_option: "ONTAPSelectEVALSmall"
vm_disk_provisioning: "thin"
vm_data_disk_gb: "500"

# blank host addresses
vcenter_address: ""
esxi_address: ""
pve_address: ""

# Network
vm_network: "VM Network"
