install_iso: "proxmox-ve_8.1-1.iso"
install_iso_url: "https://enterprise.proxmox.com/iso/proxmox-ve_8.1-1.iso"


vm_address:      
vm_netmask_cidr: 
vm_gateway:      
vm_dns_server:   
vm_domain:       
vm_hostname:     "proxmoxvm"
vm_name:         "proxmoxvm"
vm_password:     "P@ssw0rd"
