  - name: Remove old kickstart file
    file:
      path: "{{ playbook_dir }}/files/{{vm_name}}/KS.CFG"
      state: absent
    delegate_to: localhost

  - name: Remove kickstart directory
    file:
      path: "{{ playbook_dir }}/files/{{vm_name}}"
      state: absent
    delegate_to: localhost

