---
- name: build vm on vcenter
  include_tasks: vmw_main.yml
  when: 
    - vcenter_address|default('') != ''
    - vcenter_address != esxi_address
    - pve_address|default('') == ''

- name: build vm on esxi
  include_tasks: main_esxi.yml
  when: 
    - vcenter_address|default('') == '' or vcenter_address == esxi_address
    - pve_address|default('') == ''

- name: build vm on PVE
  include_tasks: pve_main.yml
  when:
    - pve_address|default('') != ''
    