---
- name: build vm on VMware
  include_tasks: vmw_main.yml
  when: 
    - vcenter_address ~ esxi_address != ''
    - pve_address == ''

- name: build vm on PVE
  include_tasks: pve_main.yml
  when:
    - pve_address != ''


    