- name: variable defaults
  set_fact:
    vm_password_new: "{{vm_password | default('P@ssw0rd') }}"
    config_iso:      "{{vm_name}}-ks.iso"

#Translate old version format to new version format
- name: set centos7 facts
  set_fact:
    distro: "centos"
    version: "7"
  when: version|lower == "centos7"

- name: set centos8 facts
  set_fact:
    distro: "centos"
    version: "8"
  when: version|lower == "centos8"

- name: set rocky8 facts
  set_fact:
    distro: "rocky"
    version: "8"
  when: version|lower == "rocky8"

- name: set alma8 facts
  set_fact:
    distro: "alma"
    version: "8"
  when: version|lower == "alma8"

- name: set rhel8 facts
  set_fact:
    distro: "rhel"
    version: "8"
  when: version|lower == "rhel8"
# end of version translation

- name: distro and version vars lookup
  set_fact:
    install_iso: "{{ lookup('vars', distro + version + '_iso') }}"
    install_iso_url: "{{ lookup('vars', distro + version + '_iso_url') }}"

- name: pve substitutions
  set_fact:
    pve_vm_datastore: "{{ datastore_substitutions[vm_datastore]|default(vm_datastore) }}"
    pve_vm_network: "{{ network_substitutions[vm_network]|default(vm_network) }}"
  when:
    - pve_address != ''

