---
- name: Add PVE Host to Dynamic Inventory
  add_host:
    hostname: temp_host
    group: "temp_hosts"
    ansible_host: '{{ pve_address }}'
    ansible_user: '{{ pve_username }}'
    ansible_password: '{{ pve_password }}'
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
    
- name: remove if absent or forced
  include_tasks: pve_absent.yml
  when: state == "absent" or state == "force"

- name: Process vars
  include_tasks: process_vars.yml
  when: state == "present" or state == "force"

- name: upload install iso
  include_tasks: pve_upload_install_iso.yml
  when: state == "present" or state == "force"

- name: create kickstart file
  include_tasks: create_kickstart.yml
  when: state == "present" or state == "force"

- name: create config iso
  include_tasks: pve_create_config_iso.yml
  when: state == "present" or state == "force"

- name: delete kickstart file
  include_tasks: delete_kickstart.yml
  when: state == "present" or state == "force"

- name: Build CentOS VM - ansible
  include_tasks: pve_build_vm.yml
  when: state == "present" or state == "force"

- name: Configure Guest
  include_tasks: pve_configure_guest.yml
  when: state == "present" or state == "force"