---
- name: Creating files directory
  file:
    path: "{{ role_path }}/files/{{vm_name}}/files"
    state: directory
  delegate_to: localhost

- name: include additional files
  copy:
    src: "{{item}}"
    dest: "{{ role_path }}/files/{{vm_name}}/files/"
  delegate_to: localhost
  with_items: "{{include_files}}"
  when: include_files|default('') != ''
  ignore_errors: true

- name: Create Config ISO
  community.general.iso_create:
    src_files:
      - "{{kickstart_file}}"
      - "{{ role_path }}/files/{{vm_name}}/files/"
    dest_iso: "{{ role_path }}/files/{{config_iso}}"
    interchange_level: 3
    joliet: 3
    vol_ident: OEMDRV
  delegate_to: localhost

- name: Copy config iso to datastore
  copy:
    src: "{{ role_path }}/files/{{config_iso}}"
    dest: "{{ iso_path }}/{{config_iso}}"
  delegate_to: temp_host

- name: delete kickstart ISO
  ansible.builtin.file:
    path: "{{ role_path }}/files/{{config_iso}}"
    state: absent
  delegate_to: localhost