---
- name: Check if install ISO exists
  community.vmware.vsphere_file:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter: "{{vcenter_datacenter}}"
    datastore: "{{ iso_datastore }}"
    path: "{{ install_iso }}"
    state: file
  register: install_iso_exists2
  delegate_to: localhost
  ignore_errors: true

- name: Add ESXi Host to Ansible Hosts for SSH
  add_host:
    name: '{{ esxi_address }}'
    group: "esx"
    ansible_user: '{{ esxi_username }}'
    ansible_password: '{{ esxi_password }}'
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  when: install_iso_exists2.failed

- name: Enable ESX SSH (TSM-SSH)
  community.vmware.vmware_host_service_manager:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    esxi_hostname: '{{ esxi_hostname }}'
    service_name: TSM-SSH
    state: present
  register: tsm_ssh_service
  delegate_to: localhost
  when: install_iso_exists2.failed

- name: Enable ESX Shell (TSM)
  community.vmware.vmware_host_service_manager:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    esxi_hostname: '{{ esxi_hostname }}'
    service_name: TSM
    state: present
  register: tsm_service
  delegate_to: localhost
  when: install_iso_exists2.failed

# Toggle the httpClient firewall rule because esxi8 will claim it is enabled when it is not
- name: Disable httpClient
  shell: 'esxcli network firewall ruleset set --enabled=false --ruleset-id=httpClient'
  delegate_to: '{{ esxi_address }}'
  when: install_iso_exists2.failed

- name: Enable httpClient
  shell: 'esxcli network firewall ruleset set --enabled=true --ruleset-id=httpClient'
  delegate_to: '{{ esxi_address }}'
  when: install_iso_exists2.failed

- name: Download the Windows Server ISO
  shell: 'wget -P /vmfs/volumes/{{ iso_datastore }} {{ install_iso_url }}'
  args:
    creates: '/vmfs/volumes/{{ iso_datastore }}/{{ install_iso }} --no-check-certificate'
  delegate_to: '{{ esxi_address }}'
  when: install_iso_exists2.failed

- name: Disable ESX SSH (TSM-SSH)
  community.vmware.vmware_host_service_manager:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    esxi_hostname: '{{ esxi_hostname }}'
    service_name: TSM-SSH
    state: absent
  delegate_to: localhost
  when: 
    - tsm_ssh_service.changed
    - install_iso_exists2.failed

- name: Disable ESX Shell (TSM)
  community.vmware.vmware_host_service_manager:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    esxi_hostname: '{{ esxi_hostname }}'
    service_name: TSM
    state: absent
  delegate_to: localhost
  when: 
    - tsm_service.changed
    - install_iso_exists2.failed
