---
- name: Create config ISO
  community.general.iso_create:
    dest_iso: "{{ playbook_dir }}/files/{{vm_name}}/{{config_iso}}"    
    src_files:
      - "{{ playbook_dir }}/files/{{vm_name}}/user-data"
      - "{{ playbook_dir }}/files/{{vm_name}}/meta-data"
    interchange_level: 4
    joliet: 3
    vol_ident: cidata
  delegate_to: localhost
