---
# - name: Build CentOS Linux VMs
#   hosts: centos
#   gather_facts: false
#   vars_files:
#     - vars/main.yml
#   tasks:
- name: Build Ubuntu VM - ansible
  include_tasks: build_vm.yml

# - name: install awx - ansible
#   block:
#   - include_tasks: tasks/install_AWX_in_CentOS7_with_vm_shell.yml
#     when: install_awx|default(false)
#   when: version|lower == "centos7"

