---
- name: Reboot-Guest
  community.vmware.vmware_guest_powerstate:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    name: '{{ vm_name }}'
    state: reboot-guest
  delegate_to: localhost
  register: reboot_guest

- name: Wait for 30 seconds
  wait_for: timeout=30
  delegate_to: localhost

- name: Wait for VMware tools to become available by name
  community.vmware.vmware_guest_tools_wait:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    name: '{{ vm_name }}'
  delegate_to: localhost
  retries: 3
  delay: 15
  register: tools_result
  until: tools_result is succeeded

- name: Wait for 30 seconds
  wait_for: timeout=30
  delegate_to: localhost
