---
- name: Wait for 1 minute
  wait_for: timeout=60
  delegate_to: localhost

- name: test vm_password
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    vm_username: "{{ vm_username }}"
    vm_password: '{{ vm_password }}'
    vm_id: '{{ vm_name }}'
    vm_shell: '/usr/bin/sh'
    vm_shell_args: " -c \"echo {{vm_password }} | sudo -S ls\""
    wait_for_process: true
  register: test_vm_password
  delegate_to: localhost 
  ignore_errors: true

- name: test vm_password_old
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    vm_username: "{{ vm_username }}"
    vm_password: '{{ vm_password_old }}'
    vm_id: '{{ vm_name }}'
    vm_shell: '/usr/bin/sh'
    vm_shell_args: " -c \"echo {{vm_password }} | sudo -S ls\""
    wait_for_process: true
  register: test_vm_password_old
  delegate_to: localhost 
  ignore_errors: true
- name: increment retry_counter
  set_fact:
    retry_counter: "{{ retry_counter|default(0)|int + 1}}"

# - debug:
#     msg:
#       - "retry_counter: {{retry_counter}}"

- name: retry number {{retry_counter}}
  include_tasks: retry_logins.yml
  when:
    - test_vm_password.failed
    - test_vm_password_old.failed

    
