---
- name: test login
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    vm_username: "{{ vm_username }}"
    vm_password: '{{ vm_password }}'
    vm_id: '{{ vm_name }}'
    vm_shell: '/usr/bin/sh'
    vm_shell_args: " -c \"echo {{vm_password }} | sudo -S ls\""
    wait_for_process: true
  retries: 60
  delay: 60
  until: test_vm_password is succeeded
  register: test_vm_password
  delegate_to: localhost 
  ignore_errors: true

