---
- name: Copy config iso to datastore
  community.vmware.vsphere_copy:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'  
    validate_certs: no 
    src: "{{ playbook_dir }}/files/{{ vm_name }}/{{ config_iso }}"
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ vm_datastore }}"
    path: "{{ config_iso }}"
  delegate_to: localhost
  ignore_errors: true #if the playbook is being re-run while the vm is on, the iso cannot be replaced
