- name: Create new VM 
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: present
    name: '{{ vm_name|replace("_", "-") }}'
    node: "{{ pve_node }}"
    net:
      net0: "virtio,bridge={{pve_networks[vm_network].bridge }}{{ (pve_networks[vm_network].vlan is defined) | ternary(',tag=' ~ (pve_networks[vm_network].vlan | default('')), '') }}"
    sata:
      sata0: '{{pve_vm_datastore}}:{{ vm_disk_gb |int }}'
    ide:
      ide2: "{{iso_datastore}}:iso/{{autoinstall_iso}},media=cdrom"
    cpu: host
    cores: '{{ vm_num_cpus|int }}'
    vcpus: '{{ vm_num_cpus|int }}'
    memory: '{{ vm_memory_mb |int}}'
    agent: true
  delegate_to: localhost
  register: create_vm
  retries: 3
  delay: 10
  until: create_vm is succeeded

- name: Attach Install ISO
  community.proxmox.proxmox_disk:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    name: '{{ vm_name|replace("_", "-") }}'
    disk: ide2
    media: cdrom
    iso_image: "{{iso_datastore}}:iso/{{autoinstall_iso}}"
  delegate_to: localhost
  retries: 3
  delay: 10
  register: result
  until: result is succeeded

# Disk order matters.
# The disk filter in the autosetup picks the first disk, so it must not be this one.
- name: Attach disks
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --sata{{ item }} {{ pve_vm_datastore }}:0,import-from={{ import_path }}/{{ vm_name }}-autoinstall.raw"
  delegate_to: temp_host
  loop:
   - 1

# Fixme: Configure Serial Ports

- name: Start VM
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: started
    name: '{{ vm_name|replace("_", "-") }}'
  delegate_to: localhost
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  ignore_errors: true

