# Remove VM(s) if state==absent or state==forced
- name: remove vm (vmw)
  include_tasks: vmw_absent.yml
  when: 
    - vcenter_address ~ esxi_address != ''
    - pve_address == ''

- name: remove vm (pve)
  include_tasks: pve_absent.yml
  when:
    - pve_address != ''
    