- name: Create new sdotconf
  copy:
    dest: "{{ playbook_dir }}/files/{{vm_name}}/sdotconf"
    content: |
      CLUSTER_NAME={{ ontap_cluster_name }}
      NODE_NAME={{ ontap_cluster_name }}-01
      ADMIN_PASSWORD={{ ontap_password }}
      CLUSTER_MGMT_IP={{ ontap_cluster_mgmt_ip }}
      CLUSTER_MGMT_NETMASK={{ ontap_netmask }}
      CLUSTER_MGMT_GATEWAY={{ ontap_gateway }}
      NODE_MGMT_IP={{ ontap_node_mgmt_ip }}
      NODE_MGMT_NETMASK={{ ontap_netmask }}
      NODE_MGMT_GATEWAY={{ ontap_gateway }}
      SERIAL_NUMBER={{ node_serial_number }}
      CLUSTER_UUID={{ ontap_cluster_mgmt_ip | ansible.builtin.to_uuid }}
      NODE_UUID={{ ontap_node_mgmt_ip | ansible.builtin.to_uuid }}
      CLUSTER_CREATE=TRUE
      NODE_COUNT=1
      NODE_LOCATION=-
      ROOT_AGGR_DISK_SIZE=69632
      CLUSTER_PORT_MTU=1500
      BUILTIN_LICENSES={{ builtin_licenses }}
      BOOTARGS=wafl-enable-sidl?={{ enable_sidl | string | lower }}
  delegate_to: localhost
  