- name: Create new setup.ngsh
  copy:
    dest: "{{ playbook_dir }}/files/{{vm_name}}/SDOTCONFIG"
    content: |
      CLUSTER_NAME=ontapselect
      NODE_NAME=ontapselect-01
      ADMIN_PASSWORD=P@ssw0rd
      CLUSTER_MGMT_IP=192.168.126.210
      CLUSTER_MGMT_NETMASK=255.255.255.0
      CLUSTER_MGMT_GATEWAY=192.168.126.1
      NODE_MGMT_IP=192.168.126.211
      NODE_MGMT_NETMASK=255.255.255.0
      NODE_MGMT_GATEWAY=192.168.126.1
      SERIAL_NUMBER=99887766554433221177
      CLUSTER_UUID=71040eab-553e-4cb6-8624-1a5cd75a21b3
      NODE_UUID=882aad6f-bf92-41dc-8163-f35524b27053
      CLUSTER_CREATE=TRUE
      NODE_COUNT=1
      NODE_LOCATION=-
      ROOT_AGGR_DISK_SIZE=69632
      CLUSTER_PORT_MTU=1500
      CLUSTER_BASE_LICENSE=UJBGVLVQJHOJKBAAAAAAAAAAAAAA
      BUILTIN_LICENSES=MPUUAKLHSOVOGDAAAAAAAAAAAAAA,SCFVEKLHSOVOGDAAAAAAAAAAAAAA,KEQYBKLHSOVOGDAAAAAAAAAAAAAA,GIHGEKLHSOVOGDAAAAAAAAAAAAAA,EXCKFKLHSOVOGDAAAAAAAAAAAAAA,UNJRDKLHSOVOGDAAAAAAAAAAAAAA,YJSJBKLHSOVOGDAAAAAAAAAAAAAA
      BOOTARGS=wafl-enable-sidl?=true
  delegate_to: localhost
