---
- name: Create Config ISO
  community.general.iso_create:
    src_files:
      - "{{ playbook_dir }}/files/{{vm_name}}/sdotconf"
    dest_iso: "{{ role_path }}/files/sdotconfig-{{vm_name}}.iso"
    interchange_level: 3
    joliet: 3
    vol_ident: OEMDRV
  delegate_to: localhost
