- name: Create new VM 
  community.proxmox.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: present
    name: '{{ vm_name|replace("_", "-") }}'
    node: "{{ pve_node }}"
    net: #'{{ networks }}'
      net0: 'virtio,bridge={{ pve_vm_network }}'
      net1: 'virtio,bridge={{ pve_vm_network }}'
      net2: 'virtio,bridge={{ pve_vm_network }}'
    serial:
      serial0: 'socket'
      serial1: 'socket'
    ide:
      ide2: "{{iso_datastore}}:iso/sdotconfig-{{vm_name}}.iso,media=cdrom"
    vga: serial0
    cpu: host
    sockets: '{{ vm_num_cpus|int }}'
    vcpus: '{{ vm_num_cpus|int }}'
    memory: '{{ vm_memory_mb |int}}'
    agent: true
    scsihw: virtio-scsi-pci
  delegate_to: localhost
  register: create_vm
  retries: 3
  delay: 10
  until: create_vm is succeeded

- debug: 
    msg: "VMID: {{ create_vm.vmid }}"

- name: import disks
  shell:  
    cmd: "qm disk import {{ create_vm.vmid }} {{ import_path }}/{{ vm_name }}-{{disk_name}}.vmdk {{pve_datastore}} --format raw"
  delegate_to: temp_host

- name: Attach disks
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi0 file={{pve_datastore}}:vm-{{create_vm.vmid}}-disk-0"
  delegate_to: temp_host

- name: Set boot order
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --bootdisk scsi0 --boot order=scsi0"
  delegate_to: temp_host

- name: Create core disk 
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi1 {{pve_datastore}}:120"
  delegate_to: temp_host

- name: Create root disk 
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi2 {{pve_datastore}}:70"
  delegate_to: temp_host

- name: Create data disk 
  shell:  
    cmd: "qm set {{ create_vm.vmid }} --scsi3 {{pve_datastore}}:{{vm_data_disk_gb}}"
  delegate_to: temp_host


  