# This prevents duplicate sysids from being used when the role is called
# multiple times within a playbook's tasks section.
- name: clear nvram_sysid
  set_fact:
    nvram_sysid: ""

- name: Remove staging directory
  file:
    path: "{{ playbook_dir }}/files/{{item}}"
    state: absent
  delegate_to: localhost
  when: item != ''
  with_items:
    - "{{vm_name}}"
    - "{{partner_name}}"