---
- name: Add PVE Host to Dynamic Inventory
  add_host:
    hostname: temp_host
    group: "temp_hosts"
    ansible_host: '{{ pve_address }}'
    ansible_user: '{{ pve_username }}'
    ansible_password: '{{ pve_password }}'
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

- name: parse vars
  include_tasks: parse_vars.yml

- name: parse pve vars
  include_tasks: pve_parse_vars.yml

- name: open OVA
  include_tasks: open_ova.yml

- name: install update
  include_tasks: install_update.yml

- name: Create setup.ngsh
  include_tasks: create_setup_ngsh.yml

- name: Set bootargs
  include_tasks: set_bootargs.yml
  when: node_name != ''
  loop_control:
    loop_var: node_name
  loop:
    - "{{vm_name}}"
    - "{{partner_name}}"

- name: update OVA
  include_tasks: update_ova.yml

- name: Build VM (vha)
  include_tasks: pve_vha_build_vm.yml
  when: 
    - disk_model == "vha"

- name: Build VM (vscsi)
  include_tasks: pve_vscsi_build_vm.yml
  when: 
    - disk_model == "vscsi"
    - partner_name == ""

- name: cleanup
  include_tasks: cleanup.yml