
- name: setenv
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/files/{{vm_name}}/env"
    regexp: "^setenv {{item.split('=')[0]}} .*$"
    line: "setenv {{item.split('=')[0]}} {{item.split('=')[1]}}"
  delegate_to: localhost
  with_items:
    # Enable VMware tools on VMware  
    - bootarg.vm.run_vmtools="true"
    # Use serial console on PVE
    # - console="comconsole,vidconsole"
    # set the node's unique identifiers
    - SYS_SERIAL_NUM="{{sys_serial_number}}"
    - bootarg.nvram.sysid="{{nvram_sysid}}"
    # configure the simulated disk shelves
    - bootarg.vm.sim.vdevinit="{{vdevinit}}"
    - bootarg.sim.vdevinit="{{vdevinit}}"
    # set automatic 4a
    - bootarg.bootmenu.allow_opts="true"
    - bootarg.bootmenu.args="4a"
    # Old method for automating 4a
    #- bootarg.init.initnextV2="true"
    #- bootarg.init.wipeclean="true"
    # make the node discoverable on the cluster network
    - bootarg.init.auto_cluster_lif.disable="false"
    # disable dhcp for node_mgmt to prevent mgmt_auto lif creation
    - bootarg.init.dhcp.disable="true"
    # Enable the setup.ngsh script
    - bootarg.setup.auto.internal="true"
    - bootarg.setup.auto.file="/cfcard/files/setup.ngsh"
    - bootarg.setup.auto="true"
    # Disable simulated disks
    - bootarg.vm.sim.vdevinit=false
    - bootarg.sim.vdevinit=false
    - bootarg.srm.disk.simnames=false
    - bootarg.srm.disk.simulated=false
    # Enable virtual disks
    - bootarg.srm.disk.config.pci=true
    - bootarg.srm.virtual.adapter=true
    - bootarg.vm.data_diskmodel=vscsi
    # Set default raid type and checksum type
    - bootarg.vm.raidtype=RAID-DP
    - bootarg.vm.checksum_type=block
    # ADP Settings
    - root-uses-shared-disks?={{adp_enabled|default('false')}}
    - allow-root-data1-data2-partitions?={{adpv2_enabled|default('false')}}
    # Twist all the kvm knobs
    # - bootarg.vm=true
    # - bootarg.vm.kvm=true
    # - bootarg.vm.qemu=true
    # - bootarg.vm.virtio_load=true

- name: enable fake-ssd
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/files/{{vm_name}}/env"
    regexp: "^setenv {{item.split('=')[0]}} .*$"
    line: "setenv {{item.split('=')[0]}} {{item.split('=')[1]}}"
  delegate_to: localhost
  with_items:
    - wafl-idedupe-allow-lowend?=true
    - allow-ssd-partitions?=true
    # This formula works for block checksum
    - fake-ssd={{ ((((fake_ssd_disk_size)-1/9)*8/9)|int)-6}}
    # This formula works for zoned checksum
    # - fake-ssd={{ (((fake_ssd_disk_size)-1/9)|int)-6}}
  when: fake_ssd_disk_size|default(0) != 0

- name: set extra bootargs
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/files/{{vm_name}}/env"
    regexp: "^setenv {{item.split('=')[0]}} .*$"
    line: "setenv {{item.split('=')[0]}} {{item.split('=')[1]}}"
  delegate_to: localhost
  with_items: "{{bootargs}}"
  when: bootargs is defined

- name: unmute console output
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/files/{{vm_name}}/env"
    regexp: "^setenv {{item.split('=')[0]}} .*$"
    line: "setenv {{item.split('=')[0]}} {{item.split('=')[1]}}"
  delegate_to: localhost
  with_items:
    - boot_verbose="true"
    - bootarg.init.console_muted="false"
  when:
    - not console_muted|default(true)
