---
- name: remove if absent or forced
  vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'    
    validate_certs: no 
    name: '{{ partner_name }}'
    state: absent
    force: yes
  delegate_to: localhost
  when: 
    - state == "absent" or force
    - partner_name|default("") != ""

- name: remove if absent or forced
  vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'    
    validate_certs: no 
    name: '{{ vm_name }}'
    state: absent
    force: yes
  delegate_to: localhost
  when: state == "absent" or force

# - meta: end_host
#   when: state == "absent"
