---
- name: parse vars
  include_tasks: parse_vars.yml

- name: extract OVA
  include_tasks: extract_ova.yml

- name: install update
  include_tasks: install_update.yml

- name: Set bootargs
  include_tasks: set_bootargs.yml
  when: node_name | default('') != ''
  loop_control:
    loop_var: node_name
  loop:
    - "{{vm_name}}"
    - "{{partner_name}}"

- name: Create setup.ngsh
  include_tasks: create_setup_ngsh.yml

- name: update OVA
  include_tasks: update_ova.yml
    
- name: Build VM (vha)
  include_tasks: vmw_vha_build_vm.yml
  when: 
    - disk_model == "vha"

- name: Build VM (vscsi)
  include_tasks: vmw_vscsi_build_vm.yml
  when: 
    - disk_model == "vscsi"
    - partner_name == ""

- name: Build VM (shared)
  include_tasks: vmw_shared_build_vm.yml
  when: 
    - disk_model == "vscsi"
    - partner_name != ""

- name: cleanup
  include_tasks: cleanup.yml
