---
- name: remove if absent
  include_tasks: vmw_absent.yml
  when: state == "absent" or state == "force"

- name: parse vars
  include_tasks: parse_vars.yml
  when: state == "present" or state == "force"

- name: open OVA
  include_tasks: open_ova.yml
  when: 
    - state == "present" or state == "force"

- name: install update
  include_tasks: install_update.yml
  when: 
    - state == "present" or state == "force"

- name: Set vha bootargs
  include_tasks: vmw_vha_bootargs.yml
  when: 
    - disk_model|default("vha") == "vha"
    - state == "present" or state == "force"

- name: Set vscsi bootargs 
  include_tasks: vmw_vscsi_bootargs.yml
  when: 
    - state == "present" or state == "force"
    - disk_model|default("vha") == "vscsi"
    - partner_name|default("") == ""

- name: Set shared HA bootargs
  include_tasks: vmw_shared_bootargs.yml
  when: 
    - state == "present" or state == "force"
    - disk_model|default("vha") == "vscsi"
    - partner_name|default("") != ""

- name: Create setup.ngsh
  include_tasks: create_setup_ngsh.yml
  when: 
    - state == "present" or state == "force"

- name: close OVA
  include_tasks: close_ova.yml
  when: 
    - state == "present" or state == "force"
    
- name: Build VM (vha)
  include_tasks: vmw_vha_build_vm.yml
  when: 
    - disk_model|default("vha") == "vha"
    - state == "present" or state == "force"

- name: Build VM (vscsi)
  include_tasks: vmw_vscsi_build_vm.yml
  when: 
    - disk_model|default("vha") == "vscsi"
    - partner_name|default("") == ""
    - state == "present" or state == "force"

- name: Build VM (shared)
  include_tasks: vmw_shared_build_vm.yml
  when: 
    - state == "present" or state == "force"
    - disk_model|default("vha") == "vscsi"
    - partner_name|default("") != ""

- name: cleanup
  include_tasks: cleanup.yml
