---
- name: Build Nested ESXI for NUC Simulation
  hosts: localhost
  gather_facts: false
  vars_files: 
    - vars/main.yml
  tasks:
    - name: Build Nested ESXI from OVA
      meta: noop
    - block:
      - include_vars: defaults/Build_Nested_ESXi_from_OVA.yml
      - set_fact:
          vm_name: TEST_NestedESXi01
          vm_network: "VM Network"
          vm_memory_mb: 32768
          vm_num_cpus: 6
          vm_disk1_size_gb: 128
          vm_disk2_size_gb: 512
          ovf_file: "files/VMware/Nested_ESXi7.0_Appliance_Template_v1.ova"
          ovf_hostname: "NestedEsxi01"
          ovf_address: 192.168.123.140
          ovf_netmask: 255.255.255.0
          ovf_gateway: 192.168.123.1 
          ovf_vlan: ""  
          ovf_dns: 192.168.123.1 
          ovf_domain: lab.local   
          ovf_ntp: 192.168.123.1
          ovf_syslog: "" # IP of syslog server
          ovf_password: P@ssw0rd
          ovf_ssh: "false"
          ovf_createvmfs: "true"
      - include_tasks: tasks/Build_Nested_ESXi_from_OVA.yml

