- name: set workspace variable
  set_fact:
    #workspace: "/tmp/esxi_iso_workspace"
    workspace: "{{ playbook_dir }}/files/{{ vm_name }}-install"
    custom_iso: "{{ vm_name }}-install.iso"
  delegate_to: localhost

- name: delete old kickstart iso
  ansible.builtin.file: 
    path: "{{ playbook_dir }}/files/{{ custom_iso }}"
    state: absent
  delegate_to: localhost

- name: remove old temporary workspace
  ansible.builtin.file:   
    path: "{{ workspace }}"
    state: absent
  delegate_to: localhost

- name: Create local temporary workspace for ESXi payload
  ansible.builtin.file:
    path: "{{ workspace }}"
    state: directory
  delegate_to: localhost

- name: Extract original VMware ISO via xorriso
  ansible.builtin.command: >
    xorriso -osirrox on -indev {{ playbook_dir }}/files/{{ install_iso }} 
    -extract / {{ workspace }}
  delegate_to: localhost

- name: Fix directory permissions to make workspace writable
  ansible.builtin.file:
    path: "{{ workspace }}"
    mode: "u+w"
    recurse: yes
  delegate_to: localhost

- name: append boot.cfg with kernel options for kickstart
  ansible.builtin.lineinfile:
    path: "{{ workspace }}/BOOT.CFG"
    regexp: '^kernelopt='
    line: "kernelopt=runweasel cdromBoot ks=file:///KS.CFG"
  delegate_to: localhost  

- name: append boot.cfg with kernel options for kickstart
  ansible.builtin.lineinfile:
    path: "{{ workspace }}/EFI/BOOT/BOOT.CFG"
    regexp: '^kernelopt='
    line: "kernelopt=runweasel cdromBoot ks=file:///KS.CFG"
  delegate_to: localhost  

- name: Append ks.cfg to modules line
  ansible.builtin.lineinfile:
    path: "{{ workspace }}/BOOT.CFG"
    regexp: '^(modules=.*)$'
    line: '\1 --- /ks.tgz'
    backrefs: true
  delegate_to: localhost

- name: Append ks.cfg to modules line
  ansible.builtin.lineinfile:
    path: "{{ workspace }}/EFI/BOOT/BOOT.CFG"
    regexp: '^(modules=.*)$'
    line: '\1 --- /ks.tgz'
    backrefs: true
  delegate_to: localhost

- name: Inject kickstart configuration file to root directory
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ vm_name }}/KS.CFG"
    dest: "{{ workspace }}/KS.CFG"
  delegate_to: localhost

- name: tgz the ks.cfg using tar command
  ansible.builtin.shell: |
    cd {{ workspace }}
    tar -czf ks.tgz KS.CFG
  delegate_to: localhost

- name: Recompile valid ESXi ISO via xorriso
  ansible.builtin.command: >
    xorriso -as mkisofs -relaxed-filenames -J -R
    -o "{{ playbook_dir }}/files/{{ custom_iso }}"
    -b ISOLINUX.BIN -c BOOT.CAT -no-emul-boot -boot-load-size 4 -boot-info-table
    -eltorito-alt-boot -e EFIBOOT.IMG -no-emul-boot
    {{ workspace }}/
  delegate_to: localhost

- name: Clean up local staging area
  ansible.builtin.file:
    path: "{{workspace}}"
    state: absent
  delegate_to: localhost

- name: Update ISO pointer fact for subsequent installation steps
  set_fact:
    install_iso: "{{ custom_iso }}"
  delegate_to: localhost
