- name: variable defaults
  set_fact:
    vm_address:      "{{vm_address      | default('') }}"
    vm_netmask:     "{{vm_netmask     | default('') }}"
    vm_netmask_cidr: "{{vm_netmask_cidr | default('') }}"
    vm_gateway:      "{{vm_gateway      | default('') }}"
    vm_dns_server:   "{{vm_dns_server   | default('') }}"
    vm_domain:       "{{vm_domain       | default('') }}"
    vm_hostname:     "{{vm_hostname     | default('esx') }}"
    vm_name:         "{{vm_name         | default('esx') }}"
    vm_password_old: "{{kickstart_password | default('Changeme!') }}"
    vm_password_new: "{{vm_password | default('P@ssw0rd') }}"
    config_iso:      "{{vm_name}}-ks.iso"

