- name: Create new VM 
  community.general.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: present
    name: '{{ vm_name|replace("_", "-") }}'
    node: "{{ pve_node }}"
    bios: ovmf
    # boot: 'order=sata0;sata5'
    efidisk0:
      storage: '{{pve_vm_datastore}}'
      format: raw
      efitype: 4m
      pre_enrolled_keys: 1
    net:
      net0: 'vmxnet3,bridge={{ pve_vm_network }}'
      net1: 'vmxnet3,bridge={{ pve_vm_network }}'
    sata:
      sata0: '{{pve_vm_datastore}}:{{ vm_disk_gb |int }}'
      # sata5: "{{iso_datastore}}:iso/{{install_iso}},media=cdrom"
      # sata4: "{{iso_datastore}}:iso/{{config_iso}},media=cdrom"
    ide:
      ide1: "{{iso_datastore}}:iso/{{install_iso}},media=cdrom"
      ide2: "{{iso_datastore}}:iso/{{config_iso}},media=cdrom"
    cpu: host
    cores: '{{ vm_num_cpus|int }}'
    vcpus: '{{ vm_num_cpus|int }}'
    memory: '{{ vm_memory_mb |int}}'
    agent: true
  delegate_to: localhost
  register: create_vm

# - name: Attach Install ISO
#   community.general.proxmox_disk:
#     api_user: '{{ pve_username }}@pam'
#     api_password: '{{ pve_password }}'
#     api_host: '{{ pve_address }}'
#     #vmid: "{{ create_vm.vmid }}"
#     name: '{{ vm_name|replace("_", "-") }}'
#     disk: ide1
#     media: cdrom
#     iso_image: "{{iso_datastore}}:iso/{{install_iso}}"
#   delegate_to: localhost

# - name: Attach Config ISO
#   community.general.proxmox_disk:
#     api_user: '{{ pve_username }}@pam'
#     api_password: '{{ pve_password }}'
#     api_host: '{{ pve_address }}'
#     #vmid: "{{ create_vm.vmid }}"
#     name: '{{ vm_name|replace("_", "-") }}'
#     disk: sata5
#     media: cdrom
#     iso_image: "{{iso_datastore}}:iso/{{config_iso}}"
#   delegate_to: localhost

- name: Start VM
  community.general.proxmox_kvm:
    api_user: '{{ pve_username }}@pam'
    api_password: '{{ pve_password }}'
    api_host: '{{ pve_address }}'
    state: started
    name: '{{ vm_name|replace("_", "-") }}'
  delegate_to: localhost
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  ignore_errors: true
  
- name: Wait for 4 seconds for menu
  wait_for: timeout=4
  delegate_to: localhost

- name: configure kernel options
  command:
    cmd: 'qm sendkey {{ create_vm.vmid }} {{item}}'
  delegate_to: temp_host
  loop: 
    - shift-o
    - spc
    - k
    - s
    - equal
    - c
    - d 
    - r
    - o
    - m
    - shift-semicolon
    - slash
    - shift-k
    - shift-s
    - dot
    - shift-c
    - shift-f
    - shift-g
    - ret
