#defaults:
state: present
install_iso: "VMware-VMvisor-Installer-9.0.0.0.24755229.x86_64.iso"
kickstart_file: "{{ role_path }}/files/{{vm_name}}/KS.CFG"
vm_disk_gb: 128

vm_network: "VM Network"
disk_controller: paravirtual
default_disks:
  - size_gb: '{{ vm_disk_gb }}'
    controller_type: '{{ disk_controller }}'
    controller_number: 0
    unit_number: 0
    type: thin
disks: "{{default_disks}}"

vm_num_nics: 2
network_device_type: "vmxnet3"
default_networks:
  - name: "{{ vm_network }}"
    device_type: "{{ network_device_type }}"
  - name: "{{ vm_network }}"
    device_type: "{{ network_device_type }}"

serial_ports: false
iso_path: /var/lib/vz/template/iso

# blank host addresses
pve_address: ""
esxi_address: ""
vcenter_address: ""
vcenter_cluster:

# vm defaults
vm_address:
vm_netmask:
vm_gateway:
vm_dns_server:
vm_domain:
vm_hostname: esx 
vm_name:     esx 
config_iso:  "{{vm_name}}-ks.iso"